### ISSUE TITLE
code:500. Error (Internal Error)

### ISSUE THREAD

**Issue by adesuwar** [Venafi/vault-pki-backend-venafi#115]
**PROBLEM SUMMARY**
<!- When I try to write to venafi-pki-backend/venafi/tpp, with all of the parameters needed, I get an error message. This issue only occurs with tokens that are not root.  

**STEPS TO REPRODUCE**
not sure about the Venafi

**COMMENTS/WORKAROUNDS**
<!-- I am able to get the cert I need with root but I need to be able to get certs from a vault namespace with a user token. 

QUESTION**
To get a cert generated, does the token have to be root?

**Comment by luispresuelVenafi** [comment]
Hi @adesuwar thank you for reaching out.
Could you share the parameters that are being set for the role and the execution and output of the error message you are getting?

**Comment by adesuwar** [comment]
Hi @luispresuelVenafi thank you for reaching out. 
vault write venafi-pki-backend/venafi/tpp \
    url="https://vas0000grwv2a.internal.corp.foo.com" \
    access_token="43591808gdYCaNMDJ3EQ==" \
    refresh_token="MnhHmg20sftrY6EW4+1A=="
    zone="Vault-Backend-Issued"

**Comment by luispresuelVenafi** [comment]
@adesuwar That's venafi secret, I was meaning the `role` (step 9 of https://github.com/Venafi/vault-pki-backend-venafi#setup)

Also, could you provide how you are executing the `issue` command and its output (where the error appears)?
