### ISSUE TITLE
Fix Plugin version secret list

### ISSUE THREAD

**Issue by cdmadrigal** [Venafi/vault-pki-backend-venafi#146]
**PROBLEM SUMMARY**
The plugin isn't being listed in the Secrets list when the plugin has a version set to it when initialized. 

**STEPS TO REPRODUCE**
```
vault write sys/plugins/catalog/secret/venafi-pki-backend sha_256="${SHA256}" command="venafi-pki-backend" version="0.12.2"
Success! Data written to: sys/plugins/catalog/secret/venafi-pki-backend
vault read --format=json /sys/plugins/catalog
{
      {
        "builtin": false,
        "name": "venafi-pki-backend",
        "sha256": "af545920446f0ff953123f88547aa14983bc227935cc2e767151f6746a659ceb",
        "type": "secret",
        "version": "v0.12.2"
      }
}
{
      "secret": [
      "ad",
      "alicloud",
      "aws",
      "azure",
      "consul",
      "gcp",
      "gcpkms",
      "kubernetes",
      "kv",
      "ldap",
      "mongodbatlas",
      "nomad",
      "openldap",
      "pki",
      "rabbitmq",
      "ssh",
      "terraform",
      "totp",
      "transit"
    ]

}
```

Notice how the venafi-vault plugin doesn't get listed under the `secret` list even though it returns type secret

**EXPECTED RESULTS**
The plugin when initialized shows up in the secret list.

**ACTUAL RESULTS**
The plugin does not show up on the secrets list. 

**ENVIRONMENT DETAILS**
Vault 1.14.2. Plugin 0.12.2

**COMMENTS/WORKAROUNDS**
Use `vault read --format=json /sys/plugins/catalog |jq .data.detailed` to get the plugin information.

**Comment by luispresuelVenafi** [comment]
Historically we are not sure to call this a bug yet, problably it is supported but we are not doing things right. I'll remove the bug tag until is confirmed with Hashi

**Comment by cdmadrigal** [comment]
After conversations with Hashicorp, this behavior is expected. Updates would need to be back within Vault itself to support the secrets list functionality.
