### ISSUE TITLE
make prod errors out

### ISSUE THREAD

**Issue by wgoulet** [Venafi/vault-pki-backend-venafi#2]
OS version:
CentOS Linux release 7.5.1804 (Core) 

Docker version:
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false

Problem Description:
When using 'make prod' per the README to setup the integration, the process fails right after the Vault containers are created. I can recover by logging into the Vault container and executing the setup steps to initialize the vault manually, but the first use experience with the make commands fails. Here is relevant output:

```
[wgoulet@linuxdesktop vault-pki-backend-venafi]$ make prod
/bin/sh: vault: command not found
Using vault client version 
docker-compose down --remove-orphans
Removing vaultpkibackendvenafi_vault_1 ... done
Removing vaultpkibackendvenafi_consul_1 ... done
Removing network vaultpkibackendvenafi_default
docker-compose up -d
Creating network "vaultpkibackendvenafi_default" with the default driver
Creating vaultpkibackendvenafi_consul_1
Creating vaultpkibackendvenafi_vault_1
Run: docker-compose logs
to see the logs
Run: docker exec -it cault_vault_1 sh
to login into vault container
Waiting until server start
sleep 10
docker exec -it $(docker-compose ps |grep Up|grep vault_1|awk '{print $1}') vault operator init -key-shares=1 -key-threshold=1
Error: No such container: vault
make: *** [prod_server_init] Error 1
```

**Comment by arykalin** [comment]
Hi @wgoulet could you check out latest code and try again?

**Comment by wgoulet** [comment]
Hi @arykalin I confirmed with latest code that make prod completes successfully. All steps to create the vault instance, install the venafi pki backend and get the vault ready for operation work.

Thanks!

**Comment by arykalin** [comment]
Great, thank you for feedback!
