### ISSUE TITLE
Typo in setup instructions

### ISSUE THREAD

**Issue by wgoulet** [Venafi/vault-pki-backend-venafi#20]
Readme.md contains as a first step to use the following commands to exact the plugin:

```
wget https://github.com/Venafi/vault-pki-backend-venafi/releases/download/v0.3-11.5-alpha.161/venafi-pki-backend_0.3-11.5.161_linux.zip
unzip venafi-pki-backend_0.3-11.5.161_linux.zip
mv vault-pki-backend-venafi /etc/vault/vault_plugins
```
The extracted filename in the archive is venafi-pki-backend, so the last command should be
`mv venafi-pki-backend /etc/vault/vault_plugins
`

**Comment by arykalin** [comment]
Fixed in https://github.com/Venafi/vault-pki-backend-venafi/pull/21
