### ISSUE TITLE
echo 'plugin_directory = "/etc/vault/vault_plugins"' > vault-config.hcl

### ISSUE THREAD

**Issue by chadmphx** [Venafi/vault-pki-backend-venafi#29]
You cannot update a config file when deployed via Helm to Kubernetes. If you access vault pod with shell, you do not have user permissions to edit file. Unable to add plugin field, so therefore unable to add Venafi plugin. Please help.

**Comment by mr-tron** [comment]
Ok. How do you configure vault now? I think you have some template, which is using for configure vault cluster. You can add `plugin_directory` parameter to the template.

**Comment by arykalin** [comment]
Hi @chadmphx what Helm template do you use to deploy the Vault? You can create configMap with Vault config and mount it into deployment. https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/

**Comment by arykalin** [comment]
@chadmphx closing it for now, if you have more questions please open new issue or write a letter to opensource@venafi.com
