### ISSUE TITLE
Possible bug using later versions of Vault

### ISSUE THREAD

**Issue by carlskii** [Venafi/vault-pki-backend-venafi#33]
Currently using `Vault v1.2.3` and tested on OSX and Linux.  Configured like this: 

```
cat /etc/vault.d/vault.hcl
ui = true
disable_mlock = true
plugin_directory = "/home/ubuntu/vault/plugins"
api_addr = "https://vault.venafidevopslab.com:8200"

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_enable = 1
  tls_cert_file = "/home/ubuntu/vault/fullchain.pem"
  tls_key_file  = "/home/ubuntu/vault/privkey.pem"
}

backend "file" {
  path = "/home/ubuntu/vault/backend"
}
```

**PROBLEM SUMMARY**
After successfully requesting certs from the vault-pki-backend-venafi using the following command: 

`vault write pki-venafi/issue/tpp common_name="madonna.venafi.example"`  

The `vault list pki-venafi/certs` command seems to no longer work and returns an empty list. 

**STEPS TO REPRODUCE**

Successfully registered and  configured the vault-pki-backend-venafi  backend. 

```
$vault write sys/plugins/catalog/venafi-pki-backend sha_256="${SHA256}" command="venafi-pki-backend"

Success! Data written to: sys/plugins/catalog/venafi-pki-backend
```

```
$vault write sys/plugins/catalog/venafi-pki-backend sha_256="${SHA256}" command="venafi-pki-backend"
Success! Data written to: sys/plugins/catalog/venafi-pki-backend
```

```
$vault secrets enable -path=pki-venafi -description="Venafi backend for certificate enrollment" -plugin-name=venafi-pki-backend plugin
Success! Enabled the venafi-pki-backend secrets engine at: pki-venafi/
```

Then creates a new role.
```
vault write pki-venafi/roles/tpp \
        generate_lease=true \
        max_ttl=2160h \
        tpp_url="https://EC2AMAZ-Q89P18M.acme.com" \
        zone="DevOps\\Vault\\Requests" \
        trust_bundle_file="trust-bundle.pem" \
        tpp_user="apiuser" \
        tpp_password="*********"
        store_by_cn="true" \
        store_by_serial="true" \
        store_pkey="true"
```
Requested a new cert:

```
$vault write pki-venafi/issue/tpp common_name="madonna.venafi.example"

WARNING! The following warnings were returned from Vault:

  * Read access to this endpoint should be controlled via ACLs as it will
  return the connection private key as it is.

  * TTL of "17519h49m57.029465s" exceeded the effective max_ttl of "768h0m0s";
  TTL value is capped accordingly

Key                  Value
---                  -----
lease_id             pki-venafi/issue/tpp/MHvdKw20v2JcoUh3VXZBvE3X
lease_duration       768h
lease_renewable      false
certificate          -----BEGIN CERTIFICATE-----
MIIFXzCCBEegAwIBAgITfgAAABNPmXq8Txpk1QAAAAAAEzANBgkqhkiG9w0BAQsF
ADBNMRMwEQYKCZImiZPyLGQBGRYDY29tMRQwEgYKCZImiZPyLGQBGRYEYWNtZTEg
MB4GA1UEAxMXYWNtZS1FQzJBTUFaLVE4OVAxOE0tQ0EwHhcNMTkxMDI5MTU1MTA0
WhcNMjExMDI4MTU1MTA0WjAuMQswCQYDVQQGEwJHQjEfMB0GA1UEAxMWbWFkb25u
YS52ZW5hZmkuZXhhbXBsZTCCASIwDQYJKoZIhvcNAQEBBQADggEP...........
```

Then tried to list certs: 

```
$vault list pki-venafi/certs/                                             
No value found at pki-venafi/certs/
```

**Comment by arykalin** [comment]
Can't reproduce with dev config. Looks like problem with persistent store.

**Comment by tr1ck3r** [comment]
@carlskii are you still able to reproduce this issue?  I was able to earlier but I can't any longer, even using Vault 1.2.3 and the 0.5.1 version of this secrets engine plugin.  We have seen cases where having both **store_by_cn** and **store_by_serial** set to true _sometimes_ causes storage of the certificate to fail as you've described.  Because of that I'm probably going to update the README so that we're only setting one or the other in the examples and to caution that you should set only one to true.

**Comment by tr1ck3r** [comment]
Issue could not be reproduced.

**Comment by cdmadrigal** [comment]
Got the same issue but not easily reproducible.
Tried with MacOS on a Dev environment and the cert list wasn't returning. Destroyed that environment and recreated and was able to retrieve the cert list following the same steps. 

Tried also on an Amazon Linux environment that has persistence with Consul. Cert list wasn't returning. I can share access to this environment for further testing if needed @tr1ck3r @arykalin

**Comment by carlskii** [comment]
Trying to reproduce but hitting a different issue in my environment. Monitor is locking up TPP API.
