### ISSUE TITLE
Error 500 when setting role

### ISSUE THREAD

**Issue by dianareider** [Venafi/vault-pki-backend-venafi#52]
**PROBLEM SUMMARY**
We are attempting to enable the Venafi plugin, but run into errors when setting up the role. We are following these instructions: https://www.vaultproject.io/docs/secrets/venafi

We are successfully able to get the Venafi engine enabled (we have tried at both the root and within a namespace), but the role fails with an error 500. 

**STEPS TO REPRODUCE**
1) Follow steps 1-7 in https://www.vaultproject.io/docs/secrets/venafi:

>wget https://github.com/Venafi/vault-pki-backend-venafi/releases/download/v0.6.2/venafi-pki-backend_v0.6.2+743_linux.zip
>unzip venafi-pki-backend_v0.6.2+743_linux.zip
>sudo mkdir -p /etc/vault/vault_plugins
>sudo cp venafi-pki-backend /etc/vault/vault_plugins
>sudo chown -R vault:vault /etc/vault/vault_plugins
>sudo chmod -R go-rwX /etc/vault/vault_plugins

>echo "plugin_directory = \"/etc/vault/vault_plugins\"" | sudo tee -a /etc/vault.d/vault.hcl > /dev/null
>sudo systemctl restart vault

(Above performed on all Vault servers)

>SHA256=$(sudo sha256sum /etc/vault/vault_plugins/venafi-pki-backend | cut -d' ' -f1)
>vault write sys/plugins/catalog/secret/venafi-pki-backend sha_256="${SHA256}" command="venafi-pki-backend"
>vault secrets enable -path=venafi-pki -plugin-name=venafi-pki-backend plugin

2) Step 8, create the role (command below - performed by on client with PowerShell and locally on server)

>vault write -ns=techmod venafi-pki/roles/tpp `
>tpp_url="https://<myserver>/vedsdk" `
>tpp_user="serviceaccount@domain.org" tpp_password='<password>' `
>zone="\\Automation\\InternalAutomation\\Vault" `
>generate_lease=true store_by_serial=true store_pkey=true `
>allowed_domains=domain.org `
>allow_subdomains=true

**EXPECTED RESULTS**
Role successfully created

**ACTUAL RESULTS**
Receive the below error:
Error writing data to venafi-pki/roles/tpp: Error making API request.

URL: PUT https://<myvaultinstance>:8200/v1/venafi-pki/roles/tpp
Code: 500. Errors:

* 1 error occurred:
* internal error

>sudo tail -n1 /var/log/vault/audit.log
>{"time":"2020-05-21T23:43:37.024959318Z","type":"response","auth":{"token_type":"default"},"request":{"id":"350ffd79-cf39-78bb-669d-4c6a54b84d82","operation":"update","client_token":"<snip>","client_token_accessor":"<snip>","namespace":{"id":"rMChS","path":"techmod/"},"path":"venafi-pki/roles/tpp","data":{"allow_subdomains":"<snip>","allowed_domains":"<snip>","generate_lease":"<snip>","store_by_serial":"<snip>","store_pkey":"<snip>","tpp_password":"<snip>","tpp_url":"<snip>","tpp_user":"<snip>","zone":"<snip>"},"remote_address":"<snip>"},"response":{},"error":"1 error occurred:\n\t* internal error\n\n"}

**ENVIRONMENT DETAILS**
OS: RHEL 7
Vault: v1.4.0
Venafi: TPP 19.2
Plugin: v0.6.2 (also tried v0.6.1)

**COMMENTS/WORKAROUNDS**
We have validated with our Venafi engineer that the service account can hit the vedsdk authentication endpoint API and return a token (manually via Postman), and Hashicorp support has validated we followed the correct steps for setup. We also did password rotations to ensure certain special characters were not causing issues, and changed the user/domain syntax - however, Venafi IIS logs never show an authentication attempt when setting up the role so we don't believe it is actually hitting the Venafi server. We can hit the Venafi instance via curl from the Vault servers without issue.

For reference, we are using CIS Hardening standards on the OS, but I have granted the vault service account full ownership of the plugin folder/file.

**Comment by tr1ck3r** [comment]
@dianareider are you able to see the Venafi specific role options (e.g. `tpp_url`, `tpp_user`, etc.) when you execute `vault path-help pki-backend/roles/tpp` ?  If not, that's probably an indication that the plugin is not usable by Vault (perhaps a permissions issue but it seems you gave it sufficient permissions).  Are you able to create the role if you don't specify a namespace?

I see a couple of issues with your role creation command syntax but I wouldn't expect either to result in the error you are seeing.  The "\\\\" at the beginning of the `zone` is not necessary (should be `zone="Automation\\InternalAutomation\\Vault"` assuming the full TPP policy folder DN is "\\VED\\Policy\\Automation\\InternalAutomation\\Vault").  Also the `store_by_cn` and `store_by_serial` parameters are deprecated as of v0.6.0 and were replaced by `no_store` and `store_by`.  The valid values for `store_by` are "serial" (default) or "cn".

Based on the details in the audit log it doesn't appear any of the parameter values are making it through to the Venafi secrets engine plugin.

**Comment by dianareider** [comment]
I couldn't reference the path directly to venafi-pki (404), but I was able to snag it via sys/mounts (below). We also put it on our root namespace with the same results - testing from root namespace below. We did also try a variety of variations on the role - I modified it to match your feedback, still no love. 

If this is an issue accessing the plugin - any thoughts for troubleshooting this further? The vault logs are not useful, and I haven't found anything useful in messages/audit/SELinux logs. 

Not sure if this is contributive or a red herring: when testing the 0.6.1 plugin, I did see some TLS handshake errors (it looks like the plugin was attempting to use the IP instead of cached vault address that includes the full name - we don't have IPs in SANs), but looks like that error went away in 0.6.2. Not sure if errors were masked due to notes saying a cert revocation error was fixed, or if they are cleared up now.

>$ vault path-help venafi-pki/roles/tpp
>Error retrieving help: Error making API request.
>
>URL: GET https://dev-vault-000013.vault.tm.dev1.premera.cloud:8200/v1/venafi-pki/roles/tpp?help=1
>Code: 404. Errors:
>
>* no handler for route 'venafi-pki/roles/tpp'

>$ vault path-help sys/mounts/venafi-pki/roles/tpp
>Request:        mounts/venafi-pki/roles/tpp
>Matching Route: ^mounts/(?P<path>.+?)$
>
>Mount a new backend at a new path.
> etc...

Some more details:
> $vault secrets enable venafi-pki
>Error enabling: Error making API request.
>
>URL: POST https://dev-vault-000013.vault.tm.dev1.premera.cloud:8200/v1/sys/mounts/venafi-pki
>Code: 400. Errors:
>
>* path is already in use at venafi-pki/

>$ vault secrets list
>Path                    Type                  Accessor                       Description
>[removed other engines for brevity]
>venafi-pki/             venafi-pki-backend    venafi-pki-backend_60a23f68    n/a

>$vault read sys/mounts
>Key                     Value
>[removed other engines for brevity]
>venafi-pki/             map[accessor:venafi-pki-backend_60a23f68 config:map[default_lease_ttl:0 force_no_cache:false max_lease_ttl:0] description: external_entropy_access:false local:false options:<nil> seal_wrap:false type:venafi-pki-backend uuid:0a787ddd-b8eb-1c0f-ff96-d288f93b7271]

For giggles:
>$vault secrets tune -default-lease-ttl=30m venafi-pki
>Success! Tuned the secrets engine at: venafi-pki/

**Comment by tr1ck3r** [comment]
Thank you @dianareider My best guess is that you don't have the same version of our plugin in the `/etc/vault/vault_plugins` directory on all of the servers in your cluster.  I'm able to reproduce your result on a standalone server by renaming the plugin binary after I've successfully registered and enabled it.  I think if one server in your cluster registers and enables the plugin, and another server in your cluster has a different version of the plugin (or doesn't have it at all) the role creation would fail with the 'internal error'.  The SHA256 checksum of our v0.6.2 plugin binary for Linux is **e8ec1b610132be2e8e266a4daa9ea854f7b5fc8a70a8adb86d08a7e6d858fc63**.

```
# SHA256=$(sha256sum /etc/vault/vault_plugins/venafi-pki-backend | cut -d' ' -f1)
# vault write sys/plugins/catalog/secret/venafi-pki-backend sha_256="${SHA256}" command="venafi-pki-backend"
Success! Data written to: sys/plugins/catalog/secret/venafi-pki-backend
# vault secrets enable -path=venafi-pki -plugin-name=venafi-pki-backend plugin
Success! Enabled the venafi-pki-backend secrets engine at: venafi-pki/
#
# vault write venafi-pki/roles/before_rename store_by=serial store_pkey=true \
>   generate_lease=true ttl=720h max_ttl=720h allowed_domains="venafi.example" \
>   tpp_url="https://tpp.venafi.example" \
>   tpp_user="local:admin" tpp_password="password" \
>   zone="DevOps\\HashiCorp Vault"
Success! Data written to: venafi-pki/roles/before_rename
#
# kill -9 $(ps aux | grep 'vault_plugins' | awk '{print $2}') 2>/dev/null
#
# cd /etc/vault/vault_plugins
# mv venafi-pki-backend venafi-pki-backend.save
#
# vault write venafi-pki/roles/after_rename store_by=serial store_pkey=true \
>   generate_lease=true ttl=720h max_ttl=720h allowed_domains="venafi.example" \
>   tpp_url="https://tpp.venafi.example" \
>   tpp_user="local:admin" tpp_password="password" \
>   zone="DevOps\\HashiCorp Vault"
Error writing data to venafi-pki/roles/after_rename: Error making API request.

URL: PUT https://vault.venafi.example/v1/venafi-pki/roles/after_rename
Code: 500. Errors:

* 1 error occurred:
        * internal error
```	
You're correct that your TPP settings don't come into play until you actually attempt to issue/sign a certificate using the role. So we're just troubleshooting the plugin setup here.

**Comment by dianareider** [comment]
When we initially set this up a couple weeks ago, we were using 0.6.2 (the latest available). I had ran the same commands across all three nodes, so they definitely had the same version.

I previously found that I could not disable any of the previously-enabled secrets engines with 0.6.2 (error 400), so this morning I stopped our cluster, overrode the plugin (on all 3 nodes) with the 0.6.1 version, and was able to remove the engines. Unfortunately I still get the same 500 error when attempting to set up the role

Error 400 when attempting to disable 0.6.2 engines:
>Error disabling secrets engine at venafi-pki/: Error making API request.
>
>URL: DELETE https://[serverfqdn]:8200/v1/sys/mounts/venafi-pki
>Code: 400. Errors:

>* Unrecognized remote plugin message:

>This usually means that the plugin is either invalid or simply
>needs to be recompiled to support the latest protocol. 

Downgrading to 0.6.1 (ran on all 3 servers, except the vault commands) and testing again:

```
$ cd ~
$ rm -rf ~/venafi-pki-backend
$ wget https://github.com/Venafi/vault-pki-backend-venafi/releases/download/v0.6.1/venafi-pki-backend_v0.6.1+735_linux.zip
$ unzip venafi-pki-backend_v0.6.1+735_linux.zip
$ sudo systemctl stop vault
$ rm -rf /etc/vault/vault_plugins/*
$ sudo cp venafi-pki-backend /etc/vault/vault_plugins
$ sudo systemctl start vault

$ $SHA256=$(sudo sha256sum /etc/vault/vault_plugins/venafi-pki-backend | cut -d' ' -f1)
$ echo $SHA256
b7b6c7494f8adc90c5e9f3c0c4fe274adc0776eec7828812cde702237f3feca6

$ vault write sys/plugins/catalog/secret/venafi-pki-backend sha_256="$SHA256" command="venafi-pki-backend"
Success! Data written to: sys/plugins/catalog/secret/venafi-pki-backend

$ vault write venafi-pki/roles/tpp \
     tpp_url="https://[serverfqdn]/vedsdk" \
     tpp_user="<account@domain>" tpp_password='<password>' \
     zone="Automation\\InternalAutomation\\Vault" \
     generate_lease=true store_pkey=true \
     allowed_domains=<domain> \
     allow_subdomains=true

Error writing data to venafi-pki/roles/tpp: Error making API request.

URL: PUT https://[serverfqdn]:8200/v1/venafi-pki/roles/tpp
Code: 500. Errors:

* 1 error occurred:
        * internal error

$ vault read sys/plugins/catalog/secret/venafi-pki-backend
Key        Value
---        -----
args       []
builtin    false
command    venafi-pki-backend
name       venafi-pki-backend
sha256     b7b6c7494f8adc90c5e9f3c0c4fe274adc0776eec7828812cde702237f3feca6

```

From the journal, showing failure to initialize the engine on startup, successful unmount, and errors when attempting to remount (that we don't see written to journal on 0.6.2):


```
Jun 08 12:06:38 [serverfqdn] vault[125477]: 2020-06-08T12:06:38.208-0700 [ERROR] core: skipping initialization on nil backend: path=venafi-pki/
Jun 08 12:06:38 [serverfqdn] vault[125477]: 2020-06-08T12:06:38.208-0700 [ERROR] core: skipping initialization on nil backend: path=venafi-pki/
Jun 08 12:06:38 [serverfqdn] vault[125477]: 2020-06-08T12:06:38.208-0700 [INFO]  core: post-unseal setup complete
Jun 08 12:06:38 [serverfqdn] vault[125477]: 2020-06-08T12:06:38.208-0700 [INFO]  replication.standby: requesting WAL stream: guard=c34dd4df
Jun 08 12:08:47 [serverfqdn] vault[125477]: 2020-06-08T12:08:47.605-0700 [INFO]  replication.standby: stream started: remote_index=488303
Jun 08 12:08:47 [serverfqdn] vault[125477]: 2020-06-08T12:08:47.630-0700 [INFO]  core: successfully unmounted: path=venafi-pki/ namespace=
Jun 08 12:10:31 [serverfqdn] vault[125477]: 2020-06-08T12:10:31.133-0700 [WARN]  secrets.venafi-pki-backend.venafi-pki-backend_18b56a9a.venafi-pki-backend: error closing client during Kill: metadata=true err="rpc error: code = Canceled desc = grpc: the client connection is closing"
Jun 08 12:10:31 [serverfqdn] vault[125477]: 2020-06-08T12:10:31.133-0700 [WARN]  secrets.venafi-pki-backend.venafi-pki-backend_18b56a9a.venafi-pki-backend: plugin failed to exit gracefully: metadata=true
Jun 08 12:10:31 [serverfqdn] vault[125477]: 2020-06-08T12:10:31.136-0700 [INFO]  core: successful mount: namespace= path=venafi-pki/ type=venafi-pki-backend
Jun 08 12:15:39 [serverfqdn] vault[125477]: 2020-06-08T12:15:39.574-0700 [ERROR] secrets.venafi-pki-backend.venafi-pki-backend_18b56a9a.venafi-pki-backend.venafi-pki-backend: plugin tls init: error="error during token unwrap request: Put https://10.23.18.73:8200/v1/sys/wrapping/unwrap: x509: cannot validate certificate for 10.23.18.73 because it doesn't contain any IP SANs" timestamp=2020-06-08T12:15:39.574-0700
Jun 08 12:15:39 [serverfqdn] vault[125477]: 2020-06-08T12:15:39.582-0700 [ERROR] core: failed to run existence check: error="Unrecognized remote plugin message:
Jun 08 12:15:39 [serverfqdn] vault[125477]: This usually means that the plugin is either invalid or simply
Jun 08 12:15:39 [serverfqdn] vault[125477]: needs to be recompiled to support the latest protocol."
```

**Comment by cdmadrigal** [comment]
@dianareider 
Can we do a sanity check to confirm what the underlying issue is.
Set your vault-config.hcl file to point to the directory you've setup your plugins in, example: 
```text
 plugin_directory = "/etc/vault/vault_plugins"
```
Start a Dev Vault instance on the same linux box as your setup. 
```bash
$ vault server -log-level=debug -dev -config=vault-config.hcl
```

In a new terminal tab on the same box, run the following: 
```bash
$ export VAULT_ADDR=http://127.0.0.1:8200
$ SHA256=$(shasum -a 256 /etc/vault/vault_plugins/venafi-pki-backend| cut -d' ' -f1)
$ vault write sys/plugins/catalog/secret/venafi-pki-backend sha_256="${SHA256}" command="venafi-pki-backend"
$ vault secrets enable -path=venafi-pki -plugin-name=venafi-pki-backend plugin
```

Now let's setup the Venafi role within Vault. I've noticed that you aren't specifying the trust bundle value in your command. This isn't always necessary but it's something to keep in mind in cases where the certificate attached to your Venafi TPP instance isn't trusted by the Vault boxes.

First let's try with the command you were using before: 
```bash 
$ vault write venafi-pki/roles/tpp \
     tpp_url="https://[serverfqdn]/vedsdk" \
     tpp_user="<account@domain>" tpp_password='<password>' \
     zone="Automation\\InternalAutomation\\Vault" \
     generate_lease=true store_pkey=true \
     allowed_domains=<domain> \
     allow_subdomains=true
```

If this fails, let's try again but add the trust_bundle_file value:
```bash
$ vault write venafi-pki/roles/tpp \
     tpp_url="https://[serverfqdn]/vedsdk" \
     tpp_user="<account@domain>" tpp_password='<password>' \
     zone="Automation\\InternalAutomation\\Vault" \
     generate_lease=true store_pkey=true \
     trust_bundle_file=<tpp_trust_bundle.pem>
     allowed_domains=<domain> \
     allow_subdomains=true
```

If this works, tear down the dev environment and try passing the same role to your standard Vault setup. If it doesn't work, i would assume there is a permissions issue with how vault is accessing the plugins folder and possibly the plugin binary.

**Comment by dianareider** [comment]
After side discussions, we found that Vault has a configuration option that changes what URL is used by plugins, documented at: https://www.vaultproject.io/docs/configuration#api_addr

After we added api_addr=<FQDN>:8200 (and cluster_addr=<FQDN>:8201) to our Vault config, we were able to register the role and generate certificates.

Thank you all for your help!
