### ISSUE TITLE
100h” TTL term is giving an error ("error":"1 error occurred:\n\t* permission denied\n\n"})

### ISSUE THREAD

**Issue by Tony-venafi** [Venafi/vault-pki-backend-venafi#64]
**PROBLEM SUMMARY**
Receiving TTL errors while using the monitor plugin. Original issue was " we can issue the cert, sign it, but can't save it in Venafi. also getting some strange warnings logged: (TTL of "2159h59m59.500822605s" exceeded the effective max_ttl of "768h"; TTL value is capped accordingly) As if it is trying to cap on TTL of logged in identity.}}"

This seemed to be resolved by editing the settings on Vault and changing the ttl value. The error no longer showed. However the new value is throwing a different error.

Now, receiving "Now ttl=”100h” term is giving an error ("error":"1 error occurred:\n\t* permission denied\n\n"}) " when attempting certificate issuance.

**STEPS TO REPRODUCE**
Change the ttl on vault to 100h. This TPP environment is hosted in Azure. Exact reproduction steps are unknown, as we only know what they are receiving when setting the TTL to 100h.
TPP version 20.2
Vault plugin version: 0.7.1

**EXPECTED RESULTS**
Expect to see regular issuance of certificates and not be getting these errors within the plugin. We know that the Venafi plugin lacks the functionality to consider the TTL settings from vault anyway, but wondering why we are getting this new permission denied error.

**ACTUAL RESULTS**
Now ttl=”100h” term is giving an error ("error":"1 error occurred:\n\t* permission denied\n\n"})

**ENVIRONMENT DETAILS**
This is an Azure environment. TPP version is 20.2 Vault plugin version is 0.7.1.

**COMMENTS/WORKAROUNDS**

**Comment by tr1ck3r** [comment]
Issue actually the Vault Monitor secrets engine which was impacted by increasing the vault server TTL to align with the validity the certificates being enrolled by TPP.  https://github.com/Venafi/vault-pki-monitor-venafi/issues/55
