### ISSUE TITLE
Certificate TTL and Private Key Storage Question

### ISSUE THREAD

**Issue by nmattingly** [Venafi/vault-pki-backend-venafi#87]
1. Does the plugin automatically store the private keys for certificates requested through this plugin?

2. Is there a way to enforce TTL on certificates issued via the plugin? We are seeing an issues where teams are requesting numerous public certificates that are consuming licenses. If no, is there a recommendation on how to address this scenario? I understand we can partially do this with this on the template side within Veanfi.

**Comment by tr1ck3r** [comment]
Hi @nmattingly if you set `store_pkey=true` on your role then our secrets engine will store the private key with the certificate when an issue request is successful.  The private key is returned along with the certificate using the standard method for getting the latter (i.e. `vault read pki/cert/<serial_number>`).  This functionality deviates from native Vault where it is recommended to use a [KV secrets engine](https://www.vaultproject.io/docs/secrets/kv) for persistent/retrievable storage of certificates and keys.

Versions 0.8.0 and above support flexible validity periods which is indicated using the standard TTL parameters.  So, assuming you are using a CA where TPP supports "specific end date" (i.e. DigiCert, Entrust CAGW and CS, Google, and Microsoft) all you should need to do is set the `ttl` and `max_ttl` parameters and the `issuer_hint` parameter (if you are using DigiCert, Entrust CS, or Microsoft) on your roles to specify the default and maximum validity of certificates.  Individual certificate requests can specify the `ttl` parameter to specify different validity periods as long as they are less than the maximum and greater than the minimum supported by the target CA.

Does that help?
